// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository.Data;

#nullable disable

namespace CashBox.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616091629_jjjjjjj")]
    partial class jjjjjjj
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CashBox.Repository.Entity.IncomeDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATE_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DocOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DOC_ON");

                    b.Property<decimal>("DocSum")
                        .HasColumnType("numeric")
                        .HasColumnName("DOC_SUM");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("ORGANIZATION_ID");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS_ID");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("SUPPLIER_ID");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("StatusId");

                    b.HasIndex("SupplierId");

                    b.ToTable("INCOME_DOCUMENT");
                });

            modelBuilder.Entity("CashBox.Repository.Entity.IncomeDocumentTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("OWNER_ID");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("PRICE");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("QUANTITY");

                    b.Property<decimal>("TotalSum")
                        .HasColumnType("numeric")
                        .HasColumnName("TOTAL_SUM");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProductId");

                    b.ToTable("INCOME_DOCUMENT_TABLE");
                });

            modelBuilder.Entity("CashBox.Repository.Entity.OutcomeDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATE_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DocOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DOC_ON");

                    b.Property<decimal>("DocSum")
                        .HasColumnType("numeric")
                        .HasColumnName("DOC_SUM");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("ORGANIZATION_ID");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS_ID");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("SUPPLIER_ID");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("SupplierId");

                    b.ToTable("OUTCOME_DOCUMENT");
                });

            modelBuilder.Entity("CashBox.Repository.Entity.OutcomeDocumentTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("OWNER_ID");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("PRICE");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("QUANTITY");

                    b.Property<decimal>("TotalSum")
                        .HasColumnType("numeric")
                        .HasColumnName("TOTAL_SUM");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProductId");

                    b.ToTable("OUTCOME_DOCUMENT_TABLE");
                });

            modelBuilder.Entity("CashBox.Repository.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("CODE");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATED_USER_ID");

                    b.Property<DateTime>("DeliveredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DELIVERED_AT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NAME");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("ORGANIZATION_ID");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("SYS_PRODUCT");
                });

            modelBuilder.Entity("CashBox.Repository.Entity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATE_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("SYS_ROLE");
                });

            modelBuilder.Entity("CashBox.Repository.Entity.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CODE");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATED_USER_ID");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("INN");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.HasKey("Id");

                    b.ToTable("SYS_SUPPLIER");
                });

            modelBuilder.Entity("CashBox.Repository.Entity.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATE_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("ROLE_ID");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("SYS_USER_ROLE");
                });

            modelBuilder.Entity("CashBox.Repository.Enum.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CODE");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("FULL_NAME");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("SHORT_NAME");

                    b.HasKey("Id");

                    b.ToTable("ENUM_STATUS");
                });

            modelBuilder.Entity("Repository.Entity.CorrencyRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATE_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("CURRENCY_ID");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DATE");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric")
                        .HasColumnName("RATE");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("INFO_CURRENCY_RATE");
                });

            modelBuilder.Entity("Repository.Entity.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("CODE");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATE_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("FULL_NAME");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("SHORT_NAME");

                    b.HasKey("Id");

                    b.ToTable("INFO_CURRENCY");
                });

            modelBuilder.Entity("RepositoryLayer.Entity.Contractor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATE_USER_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("DISTRICT_ID");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("FULL_NAME");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("INN");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<string>("Pinfl")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("PINFL");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("REGION_ID");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("SHORT_NAME");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("RegionId");

                    b.ToTable("HL_CONTRACTOR");
                });

            modelBuilder.Entity("RepositoryLayer.Entity.ContractorAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(27)
                        .HasColumnType("character varying(27)")
                        .HasColumnName("CODE");

                    b.Property<int>("ContractorId")
                        .HasColumnType("integer")
                        .HasColumnName("CONTRACTOR_ID");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATE_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("FULL_NAME");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("ContractorId");

                    b.ToTable("HL_CONTRACTOR_ACCOUNT");
                });

            modelBuilder.Entity("RepositoryLayer.Entity.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("CODE");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATE_USER_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("FULL_NAME");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("REGION");

                    b.HasKey("Id");

                    b.ToTable("INFO_DISTRICT");
                });

            modelBuilder.Entity("RepositoryLayer.Entity.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATE_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("DISTRICT_ID");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("FULL_NAME");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("INN");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("REGION_ID");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("SHORT_NAME");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("RegionId");

                    b.ToTable("INFO_ORGANIZATION");
                });

            modelBuilder.Entity("RepositoryLayer.Entity.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("CODE");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATE_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("FULL_NAME");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("SHORT_NAME");

                    b.HasKey("Id");

                    b.ToTable("INFO_REGION");
                });

            modelBuilder.Entity("RepositoryLayer.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("ADDRESS");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATED_USER_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("DateOfBirth")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("DATE_OF_BIRTH");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("FULL_NAME");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("ORGANIZATION_ID");

                    b.Property<string>("PassportSeries")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("PASSPORT_SERIES");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<string>("Pinfl")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("PINFL");

                    b.Property<string>("ShortName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("SHORT_NAME");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("SYS_USER");
                });

            modelBuilder.Entity("CashBox.Repository.Entity.IncomeDocument", b =>
                {
                    b.HasOne("RepositoryLayer.Entity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId");

                    b.HasOne("CashBox.Repository.Enum.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CashBox.Repository.Entity.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Status");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("CashBox.Repository.Entity.IncomeDocumentTable", b =>
                {
                    b.HasOne("CashBox.Repository.Entity.IncomeDocument", "IncomeDocument")
                        .WithMany("Tables")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CashBox.Repository.Entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeDocument");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CashBox.Repository.Entity.OutcomeDocument", b =>
                {
                    b.HasOne("CashBox.Repository.Enum.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CashBox.Repository.Entity.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("CashBox.Repository.Entity.OutcomeDocumentTable", b =>
                {
                    b.HasOne("CashBox.Repository.Entity.OutcomeDocument", "OutcomeDocument")
                        .WithMany("Tables")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CashBox.Repository.Entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutcomeDocument");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CashBox.Repository.Entity.Product", b =>
                {
                    b.HasOne("RepositoryLayer.Entity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CashBox.Repository.Entity.UserRole", b =>
                {
                    b.HasOne("CashBox.Repository.Entity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepositoryLayer.Entity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entity.CorrencyRate", b =>
                {
                    b.HasOne("Repository.Entity.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("RepositoryLayer.Entity.Contractor", b =>
                {
                    b.HasOne("RepositoryLayer.Entity.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepositoryLayer.Entity.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("RepositoryLayer.Entity.ContractorAccount", b =>
                {
                    b.HasOne("RepositoryLayer.Entity.Contractor", "Contractor")
                        .WithMany()
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contractor");
                });

            modelBuilder.Entity("RepositoryLayer.Entity.Organization", b =>
                {
                    b.HasOne("RepositoryLayer.Entity.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepositoryLayer.Entity.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("RepositoryLayer.Entity.User", b =>
                {
                    b.HasOne("RepositoryLayer.Entity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CashBox.Repository.Entity.IncomeDocument", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("CashBox.Repository.Entity.OutcomeDocument", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("CashBox.Repository.Entity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("RepositoryLayer.Entity.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
