ALTER TABLE "HL_CONTRACTOR_ACCOUNT" ALTER COLUMN "CREATE_USER_ID" DROP NOT NULL;

ALTER TABLE "HL_CONTRACTOR_ACCOUNT" ALTER COLUMN "CREATED_AT" DROP NOT NULL;

TRUNCATE TABLE "HL_CONTRACTOR_ACCOUNT" RESTART IDENTITY CASCADE;
