CREATE TABLE "SYS_ROLE" (
    "ID" INT PRIMARY KEY,
    "NAME" VARCHAR(100),
    "DESCRIPTION" VARCHAR(300),
	"CREATE_USER_ID" INT,
	"CREATED_AT" TIMESTAMP,
	"MODIFIED_USER_ID" INT,
	"MODIFIED_AT" TIMESTAMP
);

ALTER TABLE  "SYS_ROLE"
ALTER COLUMN "ID"
ADD GENERATED ALWAYS AS IDENTITY;

INSERT INTO "SYS_ROLE"
("NAME","DESCRIPTION","CREATE_USER_ID","CREATED_AT","MODIFIED_USER_ID","MODIFIED_AT")
VALUES
('Admin','can everything',1,NOW(),1,NOW()),
('User','only using',1,NOW(),1,NOW());