CREATE TABLE "SYS_ROLE" (
    "ID" INT PRIMARY KEY,
    "NAME" VARCHAR(100),
    "DESCRIPTION" VARCHAR(300),
	"CREATE_USER_ID" INT,
	"CREATED_AT" TIMESTAMP,
	"MODIFIED_USER_ID" INT,
	"MODIFIED_AT" TIMESTAMP
);

ALTER TABLE  "SYS_ROLE"
ALTER COLUMN "ID"
ADD GENERATED ALWAYS AS IDENTITY;