CREATE TABLE "ENUM_STATE" (
    "ID" INT PRIMARY KEY,
    "FULL_NAME" VARCHAR(500),
    "SHORT_NAME" VARCHAR(300),
	"CODE" VARCHAR(9),
	"CREATE_USER_ID" INT,
	"CREATED_AT" TIMESTAMP,
	"MODIFIED_USER_ID" INT,
	"MODIFIED_AT" TIMESTAMP
);

ALTER TABLE "ENUM_STATE"
ALTER COLUMN "CODE" TYPE VARCHAR(10);

ALTER TABLE  "ENUM_STATE"
ALTER COLUMN "ID"
ADD GENERATED ALWAYS AS IDENTITY;
