CREATE TABLE "SYS_USER_ROLE" (
    "ID" INT PRIMARY KEY,
    "USER_ID" INT
    REFERENCES "SYS_USER_ROLE"("ID"),
	"ROLE_ID" INT
    REFERENCES "SYS_ROLE"("ID"),
	"STATE_ID" INT
    REFERENCES "ENUM_STATE"("ID"),
	"CREATE_USER_ID" INT,
    "CREATED_AT" TIMESTAMP,
    "MODIFIED_USER_ID" INT,
    "MODIFIED_AT" TIMESTAMP
);
ALTER TABLE  "SYS_USER_ROLE"
ALTER COLUMN "ID"
ADD GENERATED ALWAYS AS IDENTITY;
