--ALTER TABLE "SYS_USER" ALTER COLUMN "FULL_NAME" DROP NOT NULL;
--ALTER TABLE "SYS_USER" ALTER COLUMN "SHORT_NAME" DROP NOT NULL;
--ALTER TABLE "SYS_USER" ALTER COLUMN "PINFL" DROP NOT NULL;
--ALTER TABLE "SYS_USER" ALTER COLUMN "ADRESS" DROP NOT NULL;
--ALTER TABLE "SYS_USER" ALTER COLUMN "PHONE_NUMBER" DROP NOT NULL;
--ALTER TABLE "SYS_USER" ALTER COLUMN "ORGANIZATION_ID" DROP NOT NULL;
--ALTER TABLE "SYS_USER" ALTER COLUMN "DATE_OF_BIRTH" DROP NOT NULL;
--ALTER TABLE "SYS_USER" ALTER COLUMN "PASSPORT_SERIES" DROP NOT NULL;

ALTER TABLE "SYS_USER"
ADD COLUMN "ORGANIZATION_ID" INT;

ALTER TABLE "SYS_USER"
ADD CONSTRAINT "FK_SYS_USER_INFO_ORGANIZATION_ORGANIZATION_ID"
FOREIGN KEY ("ORGANIZATION_ID")
REFERENCES "INFO_ORGANIZATION"("ID");
